export const countryCodes = {
  DE: { name: 'DE', code: '+49' },
  AR: { name: 'AR', code: '+54' },
  AU: { name: 'AU', code: '+61' },
  BR: { name: 'BR', code: '+55' },
  CA: { name: 'CA', code: '+1' },
  CN: { name: 'CN', code: '+86' },
  CO: { name: 'CO', code: '+57' },
  CR: { name: 'CR', code: '+506' },
  EC: { name: 'EC', code: '+593' },
  ES: { name: 'ES', code: '+34' },
  US: { name: 'US', code: '+1' },
  FR: { name: 'FR', code: '+33' },
  GB: { name: 'GB', code: '+44' },
  HU: { name: 'HU', code: '+36' },
  IN: { name: 'IN', code: '+91' },
  IE: { name: 'IE', code: '+353' },
  IS: { name: 'IS', code: '+354' },
  IT: { name: 'IT', code: '+39' },
  JP: { name: 'JP', code: '+81' },
  MX: { name: 'MX', code: '+52' },
  NL: { name: 'NL', code: '+31' },
  NO: { name: 'NO', code: '+47' },
  PE: { name: 'PE', code: '+51' },
  PT: { name: 'PT', code: '+351' },
  CH: { name: 'CH', code: '+41' },
  UY: { name: 'UY', code: '+598' },
};
